# 12-Dec-2024 ==== author: Brooke Genovese
##============================================================================##
# * SCRIPT FOR DETECTION TOTAL COUNTS BOXPLOTS *
##============================================================================##

# --- load libraries --- #
library(dplyr)
library(ggplot2)
library(ggview)

# --- import msdap data and format --- #

# this file is generated by msdap
# includes total counts for pep / prot per sample
pdata.file.use <- "./results/msdap_results/2024-12-05_16-30-09/samples.xlsx" 
pdata <- as.data.frame(read_excel(pdata.file.use))
rownames(pdata) <- pdata$sample_id
barplot_counts <- pdata %>%
  select(group, x1, detected_peptides, detected_proteins) # x1 = experimetal set

# Peptides - Calculating % difference compared to control group
##============================================================================##

group_peptide_totals <- barplot_counts %>%
  group_by(group) %>%
  summarize(total_peptides = sum(detected_peptides))

control_peptides <- group_peptide_totals %>%
  filter(group == "CONTROL") %>%
  pull(total_peptides) 

group_peptide_totals <- group_peptide_totals %>%
  dplyr::mutate(percentage_more = ((total_peptides - control_peptides) / control_peptides) * 100) %>%
  arrange(desc(percentage_more)) # order by percentage more detection
print(group_peptide_totals)

# --- peptide summary statistics --- #

sumpep <- barplot_counts %>%
  group_by(group) %>%
  summarise(
    median = median(detected_peptides),
    IQR = IQR(detected_peptides),
    lower_quartile = quantile(detected_peptides, 0.25),
    upper_quartile = quantile(detected_peptides, 0.75),
    min = min(detected_peptides),
    max = max(detected_peptides),
    mean = mean(detected_peptides),
    sd = sd(detected_peptides),
    n = n()  
  ) 

# --- peptide boxplot --- #

group_colors <- c(
  "TRIZOL" = "#a00f83",
  "HEAT95" = "#dd4124",
  "HEAT56" = "#F88500",
  "GAMMA" = "#BCCF21",
  "CONTROL" = "#0f85a0"
)

plot_boxpep <- ggplot(barplot_counts, aes(x = group, y = detected_peptides, fill = group)) + 
  geom_boxplot() + 
  labs(
    x = "Method",
    y = "n Detected Peptides"
  ) + 
  scale_fill_manual(values = group_colors) +   
  theme_minimal() + 
  theme(
    text = element_text(size = 12), 
    axis.text.x = element_text(angle = 45, hjust = 1), 
    legend.position = "none" 
  )
plot_boxpep <- plot_boxpep + canvas(800, 1000, units = "px")
print(plot_boxpep)
save_ggplot(plot_boxpep, "./figs/detected_peptides_d0_boxplot.png") # save the plot as an image

# Proteins - Calculating % difference compared to control group
##============================================================================##
group_protein_totals <- barplot_counts %>%
  group_by(group) %>%
  summarize(total_proteins = sum(detected_proteins))

control_proteins <- group_protein_totals %>% 
  filter(group == "CONTROL") %>%
  pull(total_proteins)

group_protein_totals <- group_protein_totals %>%
  mutate(percentage_more = ((total_proteins - control_proteins) / control_proteins) * 100) %>%
  arrange(desc(percentage_more)) 
print(group_protein_totals)

sumprot <- barplot_counts %>%
  group_by(group) %>%
  summarise(
    median = median(detected_proteins),
    IQR = IQR(detected_proteins),
    lower_quartile = quantile(detected_proteins, 0.25),
    upper_quartile = quantile(detected_proteins, 0.75),
    min = min(detected_proteins),
    max = max(detected_proteins),
    mean = mean(detected_proteins),
    sd = sd(detected_proteins),
    n = n()  
  )
print(sumprot) 

plot_boxprot <- ggplot(barplot_counts, aes(x = group, y = detected_proteins, fill = group)) + 
  geom_boxplot() + 
  labs(
    x = "Method",
    y = "n Detected Proteins"
  ) + 
  scale_fill_manual(values = group_colors) +  
  theme_minimal() + 
  theme(
    text = element_text(size = 12), 
    axis.text.x = element_text(angle = 45, hjust = 1), 
    legend.position = "none" 
  )
plot_boxprot <- plot_boxprot + canvas(800, 1000, units = "px")
print(plot_boxprot)
save_ggplot(plot_boxprot, "./figs/detected_proteins_d0_boxplot.png") 



